default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: report_hiring_development

test:
  <<: *default
  database: report_hiring_test

production:
  <<: *default
  database: report_hiring_production
  username: report_hiring
  password: <%= ENV["REPORTHIRING_DATABASE_PASSWORD"] %>
